require 'pry'
require 'nokogiri'
require 'open-uri'
require 'launchy'
require 'io/console'

require_relative '../lib/budget_bytes_cli/cli'
require_relative '../lib/budget_bytes_cli/scraper'
require_relative '../lib/budget_bytes_cli/category'
require_relative '../lib/budget_bytes_cli/recipe'
require_relative '../lib/budget_bytes_cli/array-prompter'
